version: '3.8'

services:
  uptrader:
    build: .
    container_name: uptrader_menu
    ports:
      - '8000:8000'
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
        